### ISSUE TITLE
error while Fitting RDRv model

### ISSUE THREAD

**Issue by somilm** [uzh-rpg/data_driven_mpc#12]
while running the rdrv_fitting.py in getting the following error

Traceback (most recent call last):
  File "/home/somil/mpc/cat_ws/src/data_driven_mpc/ros_gp_mpc/src/model_fitting/rdrv_fitting.py", line 134, in <module>
    main(model_name=rdrv_name, features=reg_dimensions, quad_sim_options=simulation_options, dataset_name=ds_name,
  File "/home/somil/mpc/cat_ws/src/data_driven_mpc/ros_gp_mpc/src/model_fitting/rdrv_fitting.py", line 84, in main
    ax[i].scatter(v_b[:, i], a_err_b[:, i], label='data')
  File "/home/somil/mpc/gp_mpc_venv/lib/python3.9/site-packages/matplotlib/__init__.py", line 1414, in inner
    return func(ax, *map(sanitize_sequence, args), **kwargs)
  File "/home/somil/mpc/gp_mpc_venv/lib/python3.9/site-packages/matplotlib/axes/_axes.py", line 4368, in scatter
    raise ValueError("x and y must be the same size")
ValueError: x and y must be the same size

can one please help me to resolve this error

**Comment by cheslee-z** [comment]
maybe you can close the visualize thread

**Comment by Azircarry** [comment]
> while running the rdrv_fitting.py in getting the following error
> 
> Traceback (most recent call last): File "/home/somil/mpc/cat_ws/src/data_driven_mpc/ros_gp_mpc/src/model_fitting/rdrv_fitting.py", line 134, in main(model_name=rdrv_name, features=reg_dimensions, quad_sim_options=simulation_options, dataset_name=ds_name, File "/home/somil/mpc/cat_ws/src/data_driven_mpc/ros_gp_mpc/src/model_fitting/rdrv_fitting.py", line 84, in main ax[i].scatter(v_b[:, i], a_err_b[:, i], label='data') File "/home/somil/mpc/gp_mpc_venv/lib/python3.9/site-packages/matplotlib/**init**.py", line 1414, in inner return func(ax, *map(sanitize_sequence, args), **kwargs) File "/home/somil/mpc/gp_mpc_venv/lib/python3.9/site-packages/matplotlib/axes/_axes.py", line 4368, in scatter raise ValueError("x and y must be the same size") ValueError: x and y must be the same size
> 
> can one please help me to resolve this error

I'm getting the same error, how can I fix it?

**Comment by Azircarry** [comment]
> maybe you can close the visualize thread

What exactly should I do?Please forgive me for this stupid question, but I really don't know how
